
package org.example.server_topdown;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countPersons", targetNamespace = "http://example.org/", className = "org.example.server_topdown.CountPersons")
    @ResponseWrapper(localName = "countPersonsResponse", targetNamespace = "http://example.org/", className = "org.example.server_topdown.CountPersonsResponse")
    public int countPersons();

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://example.org/", className = "org.example.server_topdown.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://example.org/", className = "org.example.server_topdown.DeletePersonResponse")
    public boolean deletePerson(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws PersonNotFoundEx_Exception
    ;

    /**
     * 
     * @param firstName
     * @param id
     * @param age
     * @return
     *     returns org.example.server_topdown.Person
     * @throws PersonExistsEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://example.org/", className = "org.example.server_topdown.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://example.org/", className = "org.example.server_topdown.AddPersonResponse")
    public Person addPerson(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "age", targetNamespace = "")
        int age)
        throws PersonExistsEx_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.example.server_topdown.Person
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://example.org/", className = "org.example.server_topdown.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://example.org/", className = "org.example.server_topdown.GetPersonResponse")
    public Person getPerson(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws PersonNotFoundEx_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.example.server_topdown.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://example.org/", className = "org.example.server_topdown.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://example.org/", className = "org.example.server_topdown.GetAllPersonsResponse")
    public List<Person> getAllPersons();

}
